
default_platform :ios


platform :ios do

  desc "Runs all the tests"
  lane :test do
     scan(
         project: "Felucia.xcodeproj",
         scheme: "Felucia-iOS",
         devices: ["iPhone 6s"],
         clean: true,
         output_directory: "build/reports",
         output_types: "html, junit",
     )
  end

end
